export const ARXIV_SUBJECT_DISPLAY_NAMES: Record<string, string> = {
    "cs.AI": "人工智能 (Artificial Intelligence)",
    "cs.CV": "计算机视觉 (Computer Vision)",
    "cs.CL": "自然语言处理 (NLP)",
    "cs.LG": "机器学习 (Machine Learning)",
    "cs.RO": "机器人学 (Robotics)",
    "cs.SE": "软件工程 (Software Engineering)",
    "cs.CR": "加密与安全 (Security)",
    "cs.HC": "人机交互 (HCI)",
    "cs.CC": "计算复杂性 (Computational Complexity)",
    "cs.CE": "计算工程与科学 (Computational Engineering)",
    "cs.CG": "计算几何 (Computational Geometry)",
    "cs.CY": "计算机与社会 (Computers and Society)",
    "cs.DM": "离散数学 (Discrete Mathematics)",
    "cs.GT": "计算机科学与博弈论 (Game Theory)",
    "cs.MS": "数学软件 (Mathematical Software)",
    "cs.PF": "系统性能 (Performance)",
    "cs.SD": "声音与音频处理 (Sound/Audio)",
    "cs.ET": "新兴技术 (Emerging Technologies)",
    "cs.GR": "计算机图形学 (Computer Graphics)",
    "cs.IR": "信息检索 (Information Retrieval)",
    "cs.IT": "信息论 (Information Theory)",
    "cs.LO": "计算机科学逻辑 (Logic in Computer Science)",
    "cs.MA": "多智能体系统 (Multiagent Systems)",
    "cs.MM": "多媒体 (Multimedia)",
    "cs.NE": "神经与进化计算 (Neural and Evolutionary Computing)",
    "cs.NI": "网络与互联网体系结构 (Networking and Internet Architecture)",
    "cs.OS": "操作系统 (Operating Systems)",
    "cs.PL": "编程语言 (Programming Languages)",
    "cs.SI": "社会与信息网络 (Social and Information Networks)",
    "cs.AR": "硬件体系结构 (Hardware Architecture)",
    "cs.DB": "数据库 (Databases)",
    "cs.DC": "分布式、并行与集群计算 (Distributed and Parallel Computing)",
    "cs.DS": "数据结构与算法 (Data Structures and Algorithms)",
    "astro-ph.CO": "宇宙学与非星系天体物理 (Cosmology)",
    "astro-ph.EP": "地球与行星天体物理 (Planetary Astrophysics)",
    "astro-ph.GA": "星系天体物理 (Astrophysics of Galaxies)",
    "astro-ph.HE": "高能天体物理现象 (High Energy Astrophysics)",
    "astro-ph.IM": "天体物理仪器与方法 (Instrumentation)",
    "astro-ph.SR": "太阳与恒星天体物理 (Solar and Stellar)",
    "cond-mat.mes-hall": "介观与纳米尺度物理 (Mesoscale Physics)",
    "cond-mat.mtrl-sci": "材料科学 (Materials Science)",
    "cond-mat.str-el": "强关联电子系统 (Strongly Correlated)",
    "cond-mat.supr-con": "超导性 (Superconductivity)",
    "econ.EM": "计量经济学 (Econometrics)",
    "econ.GN": "一般经济学 (General Economics)",
    "gr-qc": "广义相对论与量子宇宙学 (General Relativity)",
    "hep-ex": "高能物理-实验 (High Energy Physics - Exp)",
    "hep-ph": "高能物理-现象学 (High Energy Physics - Phen)",
    "hep-th": "高能物理-理论 (High Energy Physics - Theory)",
    "quant-ph": "量子物理 (Quantum Physics)",
    "math-ph": "数学物理 (Mathematical Physics)",
    "math.AG": "代数几何 (Algebraic Geometry)",
    "math.AP": "偏微分方程分析 (Analysis of PDEs)",
    "math.CA": "经典分析与常微分方程 (Classical Analysis)",
    "math.CO": "组合数学 (Combinatorics)",
    "math.CV": "复变量 (Complex Variables)",
    "math.DG": "微分几何 (Differential Geometry)",
    "math.FA": "泛函分析 (Functional Analysis)",
    "math.GM": "一般数学 (General Mathematics)",
    "math.NA": "数值分析 (Numerical Analysis)",
    "math.NT": "数论 (Number Theory)",
    "math.RT": "表示论 (Representation Theory)",
    "math.OC": "优化与控制 (Optimization)",
    "nlin.AO": "适应与自组织系统 (Adaptation)",
    "nlin.CD": "混沌动力学 (Chaotic Dynamics)",
    "nlin.PS": "模式形成与孤子 (Pattern Formation)",
    "physics.atom-ph": "原子物理 (Atomic Physics)",
    "physics.data-an": "数据分析、统计与概率 (Data Analysis)",
    "physics.flu-dyn": "流体动力学 (Fluid Dynamics)",
    "physics.ins-det": "仪器与探测器 (Instrumentation)",
    "physics.med-ph": "医学物理 (Medical Physics)",
    "physics.optics": "光学 (Optics)",
    "physics.plasm-ph": "等离子体物理 (Plasma Physics)",
    "physics.soc-ph": "物理学与社会 (Physics and Society)",
    "physics.space-ph": "空间物理 (Space Physics)",
    "q-bio.BM": "生物分子 (Biomolecules)",
    "q-bio.GN": "基因组学 (Genomics)",
    "q-bio.MN": "分子网络 (Molecular Networks)",
    "q-bio.NC": "神经元与认知 (Neurons and Cognition)",
    "stat.ML": "统计机器学习 (Stat Machine Learning)",
    "stat.OT": "其他统计学 (Other Statistics)",
    "eess.AS": "音频与语音处理 (Audio and Speech Processing)",
    "eess.IV": "图像与视频处理 (Image and Video Processing)",
    "eess.SP": "信号处理 (Signal Processing)",
    "eess.SY": "系统与控制 (Systems and Control)",
    "math.DS": "动力系统 (Dynamical Systems)",
    "math.PR": "概率论 (Probability)",
    "physics.comp-ph": "计算物理 (Computational Physics)",
    "q-bio.QM": "定量方法 (Quantitative Methods)",
    "stat.AP": "应用统计 (Applications)",
    "stat.ME": "统计方法论 (Methodology)",
};

export const getArxivSubjectDisplayName = (subject: string) => (
    ARXIV_SUBJECT_DISPLAY_NAMES[subject] || ""
);
